#!python

# Load libraries
import gc
import sys
import getopt
import itertools

import yaml

from cplate import summarise_mcmc

HELP = '''
Usage: cplate_detect_mcmc [options] CONFIG [CONFIG ...]

Options:
  -h, --help            Show this help message and exit
  -c CHROM, --chrom=CHROM
                        Comma-separated indices of chromosomes to analyze;
                        defaults to 1
  --all                 Run all chromosomes

Runs detection using existing posterior summaries

Details of the required format for the YAML CONFIG files can be found it further
documentation.
'''

def main(argv):
    '''
    Main function for option-parsing and startup.
    
    Takes sys.argv[1:] as input.
    '''
    # Set default values for options
    chrom_list = None
    run_all = False
    
    # Parse arguments and options
    opts, args = getopt.getopt(argv, "hc:", ["help", "chrom=", "all"])
    for option, value in opts:
        if option in ('-h', "--help"):
            print >> sys.stderr, HELP
            sys.exit(2)
        elif option in ('-c', '--chrom'):
            chrom_list = [int(x) for x in value.split(',')]
        elif option == '--null':
            null = True
        elif option == '--both':
            both = True
        elif option == '--all':
            run_all = True
        else:
            print >> sys.stderr, "Error -- unknown option %s" % option
            sys.exit(1)

    # Set default chrom value
    if chrom_list is None:
        chrom_list = [1]

    if len(args) > 0:
        cfg_paths = args
    else:
        print >> sys.stderr, "Error -- need path to YAML configuration"
        sys.exit(1)
    
    # Iterate over configurations
    for cfg_path in cfg_paths:
        # Parse YAML configuration
        cfg_file = open(cfg_path, 'rb')
        cfg = yaml.load(cfg_file)
        cfg_file.close()
        
        if run_all:
            chrom_list = range(1, cfg['data']['n_chrom']+1)
        
        # Iterate over chromosomes
        for chrom in chrom_list:
            # Summarise MCMC output
            summarise_mcmc.detect_from_summaries(cfg=cfg, chrom=chrom)

            # Clean-up before next chromosome
            gc.collect()

if __name__ == '__main__':
    main(sys.argv[1:])

